site_name: tbxmanager
site_url: https://tbxmanager.com
site_description: The MATLAB Package Manager
repo_url: https://github.com/kvasnica/tbxmanager
repo_name: kvasnica/tbxmanager

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands: commands.md
  - Creating Packages: creating-packages.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kvasnica/tbxmanager
